title: AI Conference Deadlines
description: Countdowns to my conference deadlines. Overview of deadlines and conference dates in a calendar.
author: Harsh Sinha

domain: "https://sinhaharsh.github.io/"
baseurl: "/conference-deadlines"

twitter:
  username: sinhaharsh_
  hashtag: machinelearning
github_username: sinhaharsh
github_repo: conference-deadlines

markdown: kramdown
ga_id: UA-166050497-2

include: ["_pages"]
exclude:
  - src
  - scripts
