title: AI Conference Deadlines
description: Countdowns to CV/NLP/ML/Robotics/AI conference deadlines. Overview of deadlines and conference dates in a calendar.
author: Alexander Naumann

domain: "https://sinhaharsh.github.io/"
baseurl: "/conference-deadlines"

twitter:
  username: AlexN4u
  hashtag: machinelearning
github_username: a-nau
github_repo: conference-deadlines

markdown: kramdown
ga_id: UA-166050497-2

include: ["_pages"]
exclude:
  - src
  - scripts
